name: AutoCorrect

on: [pull_request_target]

permissions:
  pull-requests: read
  contents: read

jobs:
  autocorrect:
    runs-on: ubuntu-latest
    steps:
    - name: Check source code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: AutoCorrect check
        run: |
          curl -sSL https://git.io/JcGER | sudo bash
          autocorrect --lint --no-diff-bg-color $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }})
