name: AutoCorrect

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: read
  contents: read

jobs:
  autocorrect:
    runs-on: ubuntu-latest
    steps:
    - name: Check source code
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Setup Nix
      uses: nixbuild/nix-quick-install-action@1f095fee853b33114486cfdeae62fa099cda35a9 # v33
    - name: AutoCorrect check
      run: |
        nix run nixpkgs#autocorrect -- \
          --lint \
          --no-diff-bg-color \
          $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }})
